import {
  type CreateReadingInput,
  type ListReadingsQuery,
  type Reading,
  type UpdateReadingInput,
  createReadingInputSchema,
  listReadingsQuerySchema,
  updateReadingInputSchema,
} from '@dorm/shared/zod';
import { Controller, Get, HttpCode, Param, ParseUUIDPipe, Patch, Post } from '@nestjs/common';
import { Roles } from '../../common/decorators/roles.decorator.js';
import { ZodBody, ZodQuery } from '../../common/decorators/zod-body.decorator.js';
import type { CursorPage } from '../../common/util/cursor.util.js';
import { ReadingService } from './reading.service.js';

/**
 * Reading endpoints — `/c/:companySlug/readings`.
 *
 * RBAC:
 *   - LIST / GET     : any authenticated admin role
 *   - POST / PATCH   : `company_owner`, `property_manager`, `staff` — staff
 *     do the monthly meter walk; this is their primary mutating endpoint.
 *
 * No DELETE — Reading may be referenced by InvoiceItem once an invoice has
 * been generated. Use a corrective PATCH (rare) or void the invoice.
 *
 * Photo handling: clients submit `photoKey` (R2 object key from a separate
 * upload-url flow). The endpoint returns the raw key; the read-time signed
 * URL is generated by a future `/readings/:id/photo-url` route (Phase 2)
 * to keep this controller focused on CRUD.
 */
@Controller('c/:companySlug/readings')
export class ReadingController {
  constructor(private readonly readingService: ReadingService) {}

  @Get()
  list(@ZodQuery(listReadingsQuerySchema) query: ListReadingsQuery): Promise<CursorPage<Reading>> {
    return this.readingService.list(query);
  }

  @Get(':id')
  getById(@Param('id', new ParseUUIDPipe()) id: string): Promise<Reading> {
    return this.readingService.getById(id);
  }

  @Post()
  @HttpCode(201)
  @Roles('company_owner', 'property_manager', 'staff')
  create(@ZodBody(createReadingInputSchema) body: CreateReadingInput): Promise<Reading> {
    return this.readingService.create(body);
  }

  @Patch(':id')
  @Roles('company_owner', 'property_manager', 'staff')
  update(
    @Param('id', new ParseUUIDPipe()) id: string,
    @ZodBody(updateReadingInputSchema) body: UpdateReadingInput,
  ): Promise<Reading> {
    return this.readingService.update(id, body);
  }
}
